### ISSUE TITLE
Call to action newsletter sign up

### ISSUE THREAD

**Issue by mariocd10** [mariocd10/shpenj#19]

**Comment by shpenj** [comment]
<script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/51ad2963602b70f125c23ef76/87631bf729e94e3469a360e27.js");</script>

**Comment by shpenj** [comment]
Here are the instructions : https://mailchimp.com/help/about-connected-sites/?_ga=2.155014968.1454793535.1548607052-830991088.1548607052#connect+your+website+builder

**Comment by mariocd10** [comment]
3bff95f9df4b48a8351e272081843d2711bab44a
